services:
  <PIPELINE_NAME>:
    build:
      args: 
        <ARG1>: ${<ARG1>}
        <ARG2>: ${<ARG2>}
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
      dockerfile: Dockerfile.<PIPELINE_NAME>
    command: /workspace/<E2E_REPO>/<PIPELINE_SCRIPT>.sh ${<ARG1>}
    environment: 
      - ${<ARG1>}=${<ARG1>}
      - ${<ARG3>}=${<ARG3>}
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=${no_proxy}
    image: ${FINAL_IMAGE_NAME}:<MODE>-<PIPELINE_NAME>
    privileged: true
    volumes: 
      - ${OUTPUT_DIR}:${OUTPUT_DIR}
      - ./<E2E_REPO>:/workspace/<E2E_REPO>
    working_dir: /workspace/<E2E_REPO>
