services:
  wafer-insight:
    build:
      args: 
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
      dockerfile: Dockerfile.wafer-insights
    command: 
    - |
      conda run -n WI python src/loaders/synthetic_loader/loader.py
      conda run --no-capture-output -n WI python src/dashboard/app.py
    entrypoint: ["/bin/bash", "-c"]
    environment: 
      - PYTHONPATH=$PYTHONPATH:$PWD
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=${no_proxy}
    image: ${FINAL_IMAGE_NAME}:inference-ubuntu-20.04
    ports: 
      - 8050:8050
    privileged: true
    volumes: 
      - ${OUTPUT_DIR}:/data
      - ./wafer-insights:/workspace/wafer-insights
    working_dir: /workspace/wafer-insights
