metadata:
  name: document-level-sentiment-analysis

proxy: nil

dataset:
  type: nfs
  logsKey: nil
  datasetKey: sst
  nfs:
    server: nil
    path: nil
    subPath: nil
    readOnly: true

workflow: 
  dataset: sst2
  model: bert-large-uncased
  num_nodes: 2
  process_per_node: 2
  ref: v1.0.0
  repo: https://github.com/intel/document-level-sentiment-analysis

volumeClaimTemplates: 
  workspace:
    resources:
      requests:
        storage: 2Gi
  output_dir:
    resources:
      requests:
        storage: 1Gi

